export const SECOND_MS = 1000;
export const SECONDS_PER_MINUTE = 60;
export const SECONDS_PER_HOUR = 3600;
export const SECONDS_PER_DAY = 86400;

export const CLOCK_TICK_MS = SECOND_MS;
export const DEFAULT_FETCH_TIMEOUT_MS = 2000;
export const KEYBOARD_SEQUENCE_TIMEOUT_MS = 800;

export const POLL_INTERVAL_ACTIVE_MS = SECOND_MS;
export const POLL_INTERVAL_IDLE_MS = 5000;
export const HOST_FILTER_DEBOUNCE_MS = 300;
export const PRESENCE_TRACKERS_REFRESH_MS = 10000;

export const LIVE_FEED_REFRESH_MS = 1500;
export const LIVE_FEED_DETAIL_TIMEOUT_MS = 1800;
export const FINISHING_SCAN_TAIL_MS = 900;

export const BANNER_AUTO_HIDE_MS = 60000;
export const SHORT_BANNER_AUTO_HIDE_MS = 2000;

export const SETTINGS_SAVE_TIMEOUT_MS = 4000;
export const HOST_META_SAVE_TIMEOUT_MS = 4000;
export const PRUNE_CLOSED_PORTS_TIMEOUT_MS = 5000;
export const PRESENCE_MANUAL_CHECK_TIMEOUT_MS = 35000;
export const PRESENCE_DEFAULT_INTERVAL_SECONDS = 10;
export const PRESENCE_MIN_INTERVAL_SECONDS = 10;
export const PRESENCE_MAX_INTERVAL_SECONDS = 10800;
export const PRESENCE_DEFAULT_TIMEOUT_MS = 3000;
export const PRESENCE_MAX_TIMEOUT_MS = 30000;

export const PROGRESS_ANIMATION_MS = 600;
export const PROGRESS_COMPLETION_HOLD_MS = 120;
export const PROGRESS_COMPLETION_FADE_MS = 240;
export const PROGRESS_PHANTOM_INTERVAL_MS = 400;
export const PROGRESS_ELAPSED_REFRESH_MS = SECOND_MS;
export const PROGRESS_HEURISTIC_STEP_MS = SECOND_MS;
